export type AtlasTile={sources:string[];mime:'image/webp'|'image/avif';col:number;row:number;cols:number;rows:number;tileWidth:number;tileHeight:number;downloadName?:string};
export type ProductionAsset={id:string;name:string;kind:'CHARACTER'|'ENVIRONMENT'|'VEHICLE'|'REFERENCE';status:'LOCKED'|'REFERENCE'|'REVIEW';description:string;atlas:AtlasTile;siteId?:string;episodeIds?:string[];sceneIds?:string[];shotIds?:string[];angleCoverage?:string[];storyUse?:string};

const CHAR_PARTS=['/api/production-media/characters'];
const SITE_PARTS=['/api/production-media/sites'];
const STORY_PARTS=['/api/production-media/storyboards'];
const charTile=(i:number,name:string):AtlasTile=>({sources:CHAR_PARTS,mime:'image/webp',col:i%3,row:Math.floor(i/3),cols:3,rows:3,tileWidth:640,tileHeight:416,downloadName:name});
const siteTile=(i:number,name:string):AtlasTile=>({sources:SITE_PARTS,mime:'image/webp',col:i%5,row:Math.floor(i/5),cols:5,rows:6,tileWidth:600,tileHeight:350,downloadName:name});
const storyTile=(i:number,name:string):AtlasTile=>({sources:STORY_PARTS,mime:'image/webp',col:i%4,row:Math.floor(i/4),cols:4,rows:4,tileWidth:640,tileHeight:337,downloadName:name});
const sixAngles=['FRONT','BACK','LEFT PROFILE','RIGHT PROFILE','3/4 LEFT','3/4 RIGHT'];

export const productionAssets:ProductionAsset[]=[
  {id:'CHR-ARGA-01',name:'Arga Pratama',kind:'CHARACTER',status:'LOCKED',description:'Master character lock Arga, 29 tahun, driver online Jakarta.',atlas:charTile(0,'CHR-ARGA-01.png'),episodeIds:['EP001'],sceneIds:['EP001-SC01','EP001-SC02','EP001-SC03','EP001-SC04','EP001-SC05','EP001-SC06','EP001-SC07','EP001-SC08'],angleCoverage:sixAngles,storyUse:'Face lock utama untuk seluruh shot Arga.'},
  {id:'CHR-SARI-01',name:'Sari',kind:'CHARACTER',status:'LOCKED',description:'Perempuan misterius ±27 tahun, rambut hitam panjang, wardrobe maroon.',atlas:charTile(1,'CHR-SARI-01.png'),episodeIds:['EP001'],sceneIds:['EP001-SC07','EP001-SC08'],shotIds:['EP001-SC08-SH01','EP001-SC08-SH02'],angleCoverage:sixAngles,storyUse:'Identitas wajah dan silhouette wajib konsisten saat reveal.'},
  {id:'CHR-HARUN-01',name:'Pak Harun',kind:'CHARACTER',status:'LOCKED',description:'Mantan sopir taksi dan sumber sejarah lama Casablanca.',atlas:charTile(2,'CHR-HARUN-01.png'),episodeIds:['EP021–EP040'],angleCoverage:sixAngles,storyUse:'Archive interview, foto lama dan origin clues.'},
  {id:'CHR-BOWO-01',name:'Bowo',kind:'CHARACTER',status:'LOCKED',description:'Teman sesama driver Arga dan anchor kehidupan normal.',atlas:charTile(3,'CHR-BOWO-01.png'),episodeIds:['EP001–EP020'],angleCoverage:sixAngles,storyUse:'Warung driver, rumor Casablanca dan investigasi awal.'},
  {id:'CHR-DIMAS-01',name:'Dimas',kind:'CHARACTER',status:'LOCKED',description:'Teknisi CCTV/security yang membuka jalur bukti visual.',atlas:charTile(4,'CHR-DIMAS-01.png'),episodeIds:['EP021–EP040'],angleCoverage:sixAngles,storyUse:'CCTV room, freeze frame dan bukti timecode 03:13.'},
  {id:'CHR-ENTITY-01',name:'Hantu Wanita — Penumpang Tanpa Wajah',kind:'CHARACTER',status:'REVIEW',description:'Master identitas depan telah disetujui: rambut hitam sangat panjang dan lebat, gaun putih bernoda merah, kuku hitam panjang. Lima angle turunan masih wajib diregenerasi.',atlas:charTile(5,'CHR-ENTITY-01.png'),episodeIds:['EP041+'],angleCoverage:['FRONT'],storyUse:'Semua scene yang memetakan CHR-ENTITY-01 wajib memakai master FRONT ini sebagai identity reference; hasil scene tetap memerlukan review dan approval terpisah.'},
  {id:'CHR-SANTOSO-01',name:'Santoso',kind:'REFERENCE',status:'REFERENCE',description:'Sopir taksi generasi lama dan kunci sejarah Pak Harun.',atlas:charTile(6,'CHR-SANTOSO-01.png'),episodeIds:['EP021+'],storyUse:'Foto/rekonstruksi masa lalu.'},
  {id:'CHR-SARI-TURN-01',name:'Sari Turnaround',kind:'REFERENCE',status:'REFERENCE',description:'Turnaround tambahan untuk tubuh, wardrobe dan silhouette Sari.',atlas:charTile(7,'CHR-SARI-TURN-01.png'),episodeIds:['EP001+'],storyUse:'Reference continuity saat image-to-video.'},
  {id:'CHR-MASTER-REF',name:'Master Character Guide',kind:'REFERENCE',status:'REFERENCE',description:'Overview karakter dan hubungan produksi 03:13 Casablanca.',atlas:charTile(8,'CHR-MASTER-REF.png'),storyUse:'Director/editor overview.'},
  {id:'ENV-001-B',name:'Casablanca Tunnel Core',kind:'ENVIRONMENT',status:'REVIEW',siteId:'SITE-001',description:'Hero tunnel/underpass Casablanca untuk momen 03:13.',atlas:siteTile(0,'ENV-001-B.png'),episodeIds:['EP001'],sceneIds:['EP001-SC06','EP001-SC08'],shotIds:['EP001-SC06-SH01','EP001-SC08-SH02'],storyUse:'Signature supernatural location.'},
  {id:'ENV-001-A',name:'Casablanca Approach',kind:'ENVIRONMENT',status:'REVIEW',siteId:'SITE-002',description:'Approach sebelum memasuki core Casablanca.',atlas:siteTile(1,'ENV-001-A.png'),episodeIds:['EP001'],sceneIds:['EP001-SC05'],shotIds:['EP001-SC05-SH01','EP001-SC05-SH02'],storyUse:'Traffic menipis dan GPS membawa Arga ke pickup 0 meter.'},
  {id:'ENV-003-A',name:'Casablanca Monochrome Tunnel',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-003',description:'Variant tunnel dingin/monochrome untuk memory atau CCTV mood.',atlas:siteTile(2,'ENV-003-A.png'),storyUse:'Alternate tunnel language.'},
  {id:'ENV-004-A',name:'Underpass Side / Exit Corridor',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-004',description:'Sisi underpass untuk entry/exit dan transitional suspense.',atlas:siteTile(3,'ENV-004-A.png'),storyUse:'Geographic continuity Casablanca.'},
  {id:'ENV-005-A',name:'Karet / Kuningan Business District',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-005',description:'Anchor kota Jakarta dan normal-life Arga.',atlas:siteTile(4,'ENV-005-A.png'),storyUse:'Establishing Jakarta sebelum horror.'},
  {id:'ENV-006-A',name:'Rasuna Said / Kuningan Boulevard',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-006',description:'Boulevard malam untuk perjalanan Arga.',atlas:siteTile(5,'ENV-006-A.png'),storyUse:'Driving transitions.'},
  {id:'ENV-007-A',name:'Thamrin Night',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-007',description:'Jakarta central business corridor malam.',atlas:siteTile(6,'ENV-007-A.png'),storyUse:'City geography and normal-life montage.'},
  {id:'ENV-008-A',name:'Bundaran HI',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-008',description:'Landmark Jakarta dengan fountain dan traffic malam.',atlas:siteTile(7,'ENV-008-A.png'),storyUse:'Strong Jakarta anchor.'},
  {id:'ENV-009-A',name:'Jakarta CBD Skyline',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-009',description:'Skyline transition untuk establishing dan travel bridge.',atlas:siteTile(8,'ENV-009-A.png'),storyUse:'City transition.'},
  {id:'ENV-010-A',name:'Stasiun Manggarai',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-010',description:'Transit/night platform untuk investigasi dan urban tension.',atlas:siteTile(9,'ENV-010-A.png'),storyUse:'Public transit scenes.'},
  {id:'ENV-011-A',name:'Menteng',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-011',description:'Area hijau/residential yang lebih sunyi.',atlas:siteTile(10,'ENV-011-A.png'),storyUse:'Quiet investigation / deceptive safety.'},
  {id:'ENV-012-A',name:'Dukuh Atas / Transit',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-012',description:'Transit platform dan urban interchange.',atlas:siteTile(11,'ENV-012-A.png'),storyUse:'Movement and city connectivity.'},
  {id:'ENV-013-A',name:'Monas / Medan Merdeka',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-013',description:'Landmark utama Jakarta.',atlas:siteTile(12,'ENV-013-A.png'),storyUse:'Wide establishing Jakarta.'},
  {id:'ENV-014-A',name:'Jakarta Public Park',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-014',description:'Ruang publik hijau untuk normal-life dan investigation pause.',atlas:siteTile(13,'ENV-014-A.png'),storyUse:'Breathing space before escalation.'},
  {id:'ENV-015-A',name:'Parkiran Gedung Kuningan',kind:'ENVIRONMENT',status:'LOCKED',siteId:'SITE-015',description:'Arga menunggu order dan ngobrol dengan Bowo.',atlas:siteTile(14,'ENV-015-A.png'),episodeIds:['EP001+'],storyUse:'Normal life / driver waiting point.'},
  {id:'ENV-016-A',name:'Lobby / Pickup Zone Gedung',kind:'ENVIRONMENT',status:'REVIEW',siteId:'SITE-016',description:'Masuk-keluar penumpang dan titik order terakhir.',atlas:siteTile(15,'ENV-016-A.png'),episodeIds:['EP001'],sceneIds:['EP001-SC03'],shotIds:['EP001-SC03-SH01'],storyUse:'Last normal pickup environment.'},
  {id:'ENV-017-A',name:'SPBU 24 Jam',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-017',description:'Isi bensin, rehat dan telepon rumah sebelum gangguan.',atlas:siteTile(16,'ENV-017-A.png'),episodeIds:['EP001+'],storyUse:'Normal-life support site.'},
  {id:'ENV-018-A',name:'Minimarket 24 Jam',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-018',description:'Beli kopi/air dan peluang pantulan supernatural pertama.',atlas:siteTile(17,'ENV-018-A.png'),episodeIds:['EP001+'],storyUse:'Reflection clue site.'},
  {id:'ENV-019-A',name:'Rumah / Kos / Apartemen Arga',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-019',description:'Safe space Arga yang kemudian ikut terganggu.',atlas:siteTile(18,'ENV-019-A.png'),episodeIds:['EP001+'],storyUse:'Mama call, phone reflection dan home intrusion.'},
  {id:'ENV-020-A',name:'Meeting Point Driver / Warung Kopi',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-020',description:'Interaksi Arga-Bowo, gosip driver dan rumor Casablanca.',atlas:siteTile(19,'ENV-020-A.png'),episodeIds:['EP002+'],storyUse:'Exposition through normal conversation.'},
  {id:'ENV-021-A',name:'Rumah / Warung Pak Harun',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-021',description:'Arsip, foto lama dan cerita Santoso.',atlas:siteTile(20,'ENV-021-A.png'),episodeIds:['EP021+'],storyUse:'Historical exposition.'},
  {id:'ENV-022-A',name:'Ruang CCTV / Security Dimas',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-022',description:'Freeze frame, timecode 03:13 dan bukti pantulan.',atlas:siteTile(21,'ENV-022-A.png'),episodeIds:['EP021+'],storyUse:'Investigation evidence hub.'},
  {id:'ENV-023-A',name:'Basement / Loading Dock Gedung',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-023',description:'Transisi gelap; Sari dapat muncul sekilas di belakang Arga.',atlas:siteTile(22,'ENV-023-A.png'),episodeIds:['EP021+'],storyUse:'Thriller transition.'},
  {id:'ENV-024-A',name:'Lorong Servis / Pintu Beton Bawah Casablanca',kind:'ENVIRONMENT',status:'REFERENCE',siteId:'SITE-024',description:'Akses mitologi utama, origin reveal dan 13 nama.',atlas:siteTile(23,'ENV-024-A.png'),episodeIds:['EP031+'],storyUse:'Mythology core.'},
  {id:'ENV-025-A',name:'Jalan Servis / Flyover / Skyline Transition',kind:'ENVIRONMENT',status:'REVIEW',siteId:'SITE-025',description:'Driving transition dan continuity geography Jakarta.',atlas:siteTile(24,'ENV-025-A.png'),episodeIds:['EP001'],sceneIds:['EP001-SC01'],shotIds:['EP001-SC01-SH01'],storyUse:'Opening city movement.'},
  {id:'VEH-ARGA-01',name:'Interior Mobil Arga',kind:'VEHICLE',status:'REVIEW',siteId:'SET-CAR',description:'Hero set mobil: dashboard, spion, jok, phone holder dan posisi kemudi.',atlas:siteTile(25,'VEH-ARGA-01.png'),episodeIds:['EP001'],sceneIds:['EP001-SC01','EP001-SC02','EP001-SC03','EP001-SC04','EP001-SC06','EP001-SC07','EP001-SC08'],storyUse:'Recurring locked production set.'}
];

const shotOrder=['EP001-SC01-SH01','EP001-SC01-SH02','EP001-SC02-SH01','EP001-SC02-SH02','EP001-SC03-SH01','EP001-SC03-SH02','EP001-SC04-SH01','EP001-SC04-SH02','EP001-SC05-SH01','EP001-SC05-SH02','EP001-SC06-SH01','EP001-SC06-SH02','EP001-SC07-SH01','EP001-SC07-SH02','EP001-SC08-SH01','EP001-SC08-SH02'];
export function storyboardTileForShot(shotId:string){const i=shotOrder.indexOf(shotId);return i<0?null:storyTile(i,`${shotId}.png`)}
export function productionAssetById(id:string){return productionAssets.find(asset=>asset.id===id)}
