export const actualCharacterAngles=['FRONT','BACK','LEFT PROFILE','RIGHT PROFILE','3/4 LEFT','3/4 RIGHT'] as const;

const characterSlugByAssetId:Record<string,string>={
  'CHR-ARGA-01':'arga',
  'CHR-SARI-01':'sari',
  'CHR-HARUN-01':'pak-harun',
  'CHR-BOWO-01':'bowo',
  'CHR-DIMAS-01':'dimas',
  'CHR-ENTITY-01':'penumpang-tanpa-wajah',
};

const angleFileByLabel:Record<string,string>={
  'FRONT':'front',
  'BACK':'back',
  'LEFT PROFILE':'left-profile',
  'RIGHT PROFILE':'right-profile',
  '3/4 LEFT':'three-quarter-left',
  '3/4 RIGHT':'three-quarter-right',
};

/**
 * Native standalone character image generated by GitHub Actions.
 * No CSS atlas cropping is used for the six locked character angles.
 */
export function characterAngleImage(assetId:string,angle:string){
  const slug=characterSlugByAssetId[assetId];
  const file=angleFileByLabel[angle];
  if(!slug||!file) return null;
  return `/production-assets/individual/characters/${slug}/${file}.webp`;
}

/**
 * EP001 stores two shots per scene but the generated media bundle is flattened
 * to SH01-SH16. Convert the database shot id to its standalone 9:16 image.
 */
export function storyboardImageForShot(shotId:string){
  const match=/^EP001-SC(\d{2})-SH(\d{2})$/.exec(shotId);
  if(!match) return null;
  const scene=Number(match[1]);
  const shot=Number(match[2]);
  if(scene<1||scene>8||shot<1||shot>2) return null;
  const index=(scene-1)*2+shot;
  return `/production-assets/individual/storyboards/EP001/SH${String(index).padStart(2,'0')}.webp`;
}
