import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getAsset, getShot } from '@/lib/data';
import { AssetVisual } from '@/components/AssetVisual';
import { AtlasVisual } from '@/components/AtlasVisual';
import { CopyButton } from '@/components/CopyButton';
import { ReviewControls } from '@/components/ReviewControls';
import { StatusBadge } from '@/components/StatusBadge';
import { productionAssetById } from '@/lib/production-assets';
import { storyboardMedia } from '@/lib/media-manifest';

export default async function ShotPage({ params }:{ params:Promise<{shotId:string}> }){
  const { shotId }=await params; const shot=getShot(shotId); if(!shot) notFound();
  const storyMedia=storyboardMedia(shot.id);
  const refs=shot.assetIds.map(id=>({id,production:productionAssetById(id),fallback:getAsset(id)}));
  return <div className="page"><header className="hero compact"><div><span className="eyebrow accent">VERTICAL SHOT DETAIL</span><h1>{shot.id}</h1><p>{shot.timecode} • Story clock {shot.storyClock} • {shot.duration}s • master frame 9:16</p></div><StatusBadge status={shot.status}/></header><div className="shotDetail"><section className="shotCanvas verticalShotCanvas">{storyMedia?<AssetVisual src={storyMedia.src} alt={`${shot.id} vertical master`} ratio="9:16" fit="contain" className="storyboardVerticalMedia" label={storyMedia.state}/>:<div className="emptyState">SOURCE REQUIRED • {shot.id}</div>}<div className="shotFacts"><span>{shot.camera}</span><span>{shot.locationId}</span><span>{shot.environmentId}</span><span>{shot.horror}</span><span>{storyMedia?`${storyMedia.width}×${storyMedia.height} • ${storyMedia.state}`:'SOURCE REQUIRED'}</span></div><h2>{shot.action}</h2><p className="muted">Audio: {shot.audio}</p></section><aside className="inspector"><span className="eyebrow">REFERENCE ASSETS</span><p className="muted inspectorHint">Environment/reference assets may temporarily retain native ratio/legacy atlas. The storyboard master itself must always come from the standalone manifest path.</p><div className="referenceGrid">{refs.map(ref=><div key={ref.id}>{ref.production?<AtlasVisual tile={ref.production.atlas} alt={ref.production.name}/>:ref.fallback?<AssetVisual src={ref.fallback.url} alt={ref.fallback.name}/>:null}<strong>{ref.id}</strong><small>{ref.production?.name||ref.fallback?.name||'Reference'}</small></div>)}</div></aside></div><section className="promptPanel"><div className="sectionHead"><div><span className="eyebrow">AI VIDEO PROMPT</span><h2>Vertical 9:16 generation prompt</h2></div><CopyButton value={`${shot.prompt}\nOUTPUT FORMAT: vertical 9:16 composition. Preserve full subject and required environment inside safe frame. Do not crop face, hands, or story-critical props.`}/></div><pre>{shot.prompt}{'\n\n'}OUTPUT FORMAT: vertical 9:16 composition. Preserve full subject and required environment inside safe frame. Do not crop face, hands, or story-critical props.</pre><div className="continuity"><strong>Continuity:</strong> {shot.continuity}</div><div className="cardActions"><Link className="button button-secondary" href={`/api/export/${shot.id}`}>Download shot JSON</Link></div></section><section className="reviewPanel"><span className="eyebrow">REVIEW</span><ReviewControls initial={shot.status}/><p className="muted">MVP: status control is local UI state. Phase 2 persists approvals, comments, and version history in PostgreSQL.</p></section></div>;
}
